name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Build and Test
      working-directory: ${{ github.workspace }}/Assignment1
      run: |
        rm -rf build
        mkdir -p build
        
        cd build
        cmake .. -DUSE_SYSTEM_GTEST=ON
        cmake --build . --config Release
        
        ctest --output-on-failure